apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp-pod
  labels:
     app: nodejsapp
     
spec:
  template:
     metadata:
       name: nodejsapp-pod
       labels: 
         app: nodejsapp
         type: backend-end
     spec:
         containers:
           - name: nodejsapp-pod
             image: "atul0401/devopstask"
         imagePullSecrets:
           - name: regcred

  replicas: 1
  selector:
    matchLabels:
      app: nodejsapp
      

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejsapp
  ports:
    - protocol: TCP
      targetPort: 4000
      port: 4000
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
  - host: www.boilerplate.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodejs-service
            port:
              number: 4000
      
